ryada/Controllers/BooksController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ryada.Models;
using ryada.Services;

namespace ryada.Controllers
{
    public class BooksController : Controller
    {
        private readonly AppDBContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly BookService _bookService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SearchService _searchService;


        public BooksController(UserManager<IdentityUser> userManager,AppDBContext postDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _context = postDbContext;
            _hostEnvironment = webHostEnvironment;
            _userManager = userManager;

        }
        public async Task<IActionResult> Index(string? search)
        {
         
            return View(await _bookService.GetBooksAsync(search ?? ""));
        }

        [HttpGet]
        public IActionResult Add()
        {
            List<Category> categories = _context.Categories.ToList();

            BookDTO addPostVM = new BookDTO();
            addPostVM.categories = new SelectList(categories, "Id", "Name");


            return View(addPostVM);
        }
        [HttpPost]
        public async Task<IActionResult> AddAsync(BookDTO post)
        {

            var user = await _userManager.GetUserAsync(User);
            var userId = user.Id;
            var Added = new Book
                {
                Title = post.Title,
                CategoryId = post.CategoryId,
                Price = post.Price,
                Quantity = post.Quantity,
                Author = post.Author,
                InsertById = userId,

            };


            _context.Books.Add(Added);

            _context.SaveChanges();


            _context.SaveChanges();

            TempData["success"] = "Successfully Added";
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Remove(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
    }
}

ryada/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using ryada.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ryada.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly AppDBContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public CategoriesController(AppDBContext postDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _context = postDbContext;
            _hostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Category> categories =
                _context.Categories.ToList();

            return View(categories);
        }
        [HttpGet]
        public IActionResult Add()
        {

            CategoryDTO categoryDTO = new CategoryDTO();


            return View(categoryDTO);
        }
        [HttpPost]
        public IActionResult Add(CategoryDTO category)
        {
            var categoryAdded = new Category
            {
                Name = category.Name,
                InsertById= "cc9c29e3-87b0-4dc2-80d0-bcf1cef9f5d5",
            };
            _context.Categories.Add(categoryAdded);

            _context.SaveChanges();

            TempData["success"] = "Successfully Added";
            return RedirectToAction(nameof(Index));
        }
        
        public async Task<IActionResult> Remove(int id)
        {
            var categories = await _context.Categories.FindAsync(id);
            List<Book> restaurants = _context.Books.Where(x=> x.CategoryId==id).ToList();

            if (restaurants.Count>0)
            {
                TempData["Message"] = "لا يمكن حدف لانه مرتبط بجداول اخرى ";
                TempData["stats"] = "danger";

            }
            else
            {
                TempData["Message"] = "تم الحدف بنجاح";
                TempData["stats"] = "success";
                _context.Categories.Remove(categories);
                await _context.SaveChangesAsync();
            }
            
            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Edit(int id)
        {

            Category addCategory = await _context.Categories.SingleOrDefaultAsync(x => x.Id == id);

            return View(addCategory);
        }
        public async Task<IActionResult> EditSubmit(Category myCategory, int id)
        {
            var Exsit = await _context.Categories.SingleOrDefaultAsync(x => x.Id == id);
            Exsit.Name = myCategory.Name;
            _context.Categories.Update(Exsit);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
            ;
        }
    }
}

ryada/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ryada.Models;

namespace ryada.Controllers
{
    public class OrdersController : Controller
    {
        private readonly AppDBContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly UserManager<IdentityUser> _userManager;



        public OrdersController(UserManager<IdentityUser> userManager, AppDBContext postDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _context = postDbContext;
            _hostEnvironment = webHostEnvironment;
            _userManager = userManager;

        }
        public IActionResult Index()
        {
            List<order> posts = _context.orders.Include(x=> x.Post)
                .ToList();

            return View(posts);
        }

        [HttpGet]
        public IActionResult Add()
        {
            List<Book> books = _context.Books.ToList();

            OrderDTO addOrder = new OrderDTO();
            addOrder.Books = new SelectList(books, "Id", "Title");
            return View(addOrder);
        }
        [HttpPost]
        public async Task<IActionResult> AddAsync(order post)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user.Id;
            post.InsertById = userId;
            var book = await _context.Books.FindAsync(post.BookId);

            post.TotalPrice = (int)(post.Quantity* book.Price);
            _context.orders.Add(post);
            _context.SaveChanges();

            TempData["success"] = "Successfully Added";
            TempData["stats"] = "success";

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Remove(int id)
        {
            var order = await _context.orders.FindAsync(id);
            _context.orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));        
        }

        public async Task<IActionResult> Edit(int id)
        {

            order addOrder = await _context.orders.SingleOrDefaultAsync(x => x.Id == id);
            List<Book> books = _context.Books.ToList();

            ViewBag.listBooks = new SelectList(books, "Id", "Title");

            return View(addOrder);
        }
        public async Task<IActionResult> EditSubmit(order myOrder, int id)
        {
            var Exsit = await _context.orders.SingleOrDefaultAsync(x => x.Id == id);
            Exsit.Quantity = myOrder.Quantity;
            Exsit.BookId = myOrder.BookId;
            _context.orders.Update(Exsit);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
            ;
        }
    }
}

ryada/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ryada</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ryada.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ryada</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="account" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="account" asp-action="login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="account" asp-action="register">Register</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Books">Books</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Categories">Categories</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Orders">Orders</a>
                                </li>
                            </ul>
                        }

                    </div>
                </div>
            </nav>


            @if (TempData["Message"] != null)
            {
                <div class="alert alert-@TempData["stats"]" role="alert">
                    @TempData["Message"]
                </div>
            }

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1444 - ryada - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ryada/Views/Shared/_paging.cshtml
@using ryada.Controllers
@model PagintingFooterModel
@{
    string prev = Model.Previous == "disabled" ? "false" : "true";
    string nxt = Model.Next == "disabled" ?  "false" : "true";
}
<a asp-action="Index" asp-route-pageNumber="@(Model.PageID - 1)" class="button is-link @(prev == "false"? "is-light": "")" onclick='return @prev'>
Previous
</a>
    @if(Model.TotalPages<5){
    @for (int i = 1; i <= Model.TotalPages; i++)
    {
            <a asp-action="Index" asp-route-pageNumber="@i" class="button is-link @(Model.PageID != i? "is-light": "")">
                @i
             </a>
    }}
    else{
        <a asp-action="Index" asp-route-pageNumber="1" class="button is-link @(Model.PageID != 1? "is-light": "")">
            1
         </a>
    @if (Model.PageID == 1 || Model.PageID==2){
        @for (int i = 2; i <= 4; i++)
        {
             <a asp-action="Index" asp-route-pageNumber="@i" class="button is-link @(Model.PageID != i? "is-light": "")">
             @i
             </a>
        }   

        <span> ... </span>
    }
    else
    {
        if (Model.PageID >3)
        {
            <span> ... </span>
        } if (Model.PageID > 4)
            {
        <a asp-action="Index" asp-route-pageNumber="@(Model.PageID - 2)" class="button is-link is-light">
            @(Model.PageID - 2)
        </a> }
        <a asp-action="Index" asp-route-pageNumber="@(Model.PageID - 1)" class="button is-link is-light" >
            @(Model.PageID - 1)
        </a>
        if (Model.PageID <= Model.TotalPages - 1)
        {
            <a asp-action="Index" asp-route-pageNumber="@(Model.PageID)" class="button is-link" >
                @(
            Model.PageID
            )
            </a>}
        if (Model.PageID <= Model.TotalPages -2)
        {
            <a asp-action="Index" asp-route-pageNumber="@(Model.PageID + 1)" class="button is-link is-light">
                @(Model.PageID + 1)
        </a>}
        if (Model.PageID < Model.TotalPages - 2)
        {
             <span> ... </span>
        }
       

    }


         <a asp-action="Index" asp-route-pageNumber="@Model.TotalPages" class="button is-link @(Model.PageID != Model.TotalPages? "is-light": "")">
            @Model.TotalPages
          </a>
    }
<a asp-action="Index" asp-route-pageNumber="@(Model.PageID + 1)" class="button is-link @(nxt == "false"? "is-light": "")" onclick='return @nxt'>
    Next</a>